# SPDX-FileCopyrightText: 2024 Jonas Fierlings <fnoegip@gmail.com>
#
# SPDX-License-Identifier: CC0-1.0

version = 1

[[annotations]]
path = ["docs/logo/gingerbread.aseprite", "docs/logo/gingerbread.png"]
SPDX-FileCopyrightText = "2024 Jonas Fierlings <fnoegip@gmail.com>"
SPDX-License-Identifier = "CC-BY-4.0"
